### ISSUE TITLE
想问一下怎么解决

### ISSUE THREAD

**Issue by APPTOOSTILL** [Mayandev/flomo-cli#2]
✖ Failed! Maybe you have reached the 100 limit
Error: connect ECONNREFUSED 127.0.0.1:1080
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 1080,

出现这种报错，要怎么解决

**Comment by Mayandev** [comment]
> ✖ Failed! Maybe you have reached the 100 limit
> Error: connect ECONNREFUSED 127.0.0.1:1080
> at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
> errno: -111,
> code: 'ECONNREFUSED',
> syscall: 'connect',
> address: '127.0.0.1',
> port: 1080,
> 
> 出现这种报错，要怎么解决

你好像设置了全局的代理，关掉试试。或者试试 ping 一下 flomo 的域名。

```console
ping flomoapp.com
```

**Comment by APPTOOSTILL** [comment]
万分感谢，终于解决了
